const express = require('express')
const router = express.Router()

router.post('/generate', async (req, res) => {
  const { name, skills, matchedSkills, jobTitle, summary } = req.body

  try {
    const PDFDocument = require('pdfkit')
    const doc = new PDFDocument({ margin: 50 })

    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', 'attachment; filename=liveproof-resume.pdf')

    doc.pipe(res)

    // Header
    doc.fontSize(28).font('Helvetica-Bold').text(name || 'Candidate', { align: 'left' })
    doc.fontSize(14).font('Helvetica').fillColor('#0ea5e9').text(jobTitle || 'Professional', { align: 'left' })
    doc.moveDown(0.5)
    doc.moveTo(50, doc.y).lineTo(560, doc.y).strokeColor('#0ea5e9').lineWidth(2).stroke()
    doc.moveDown(0.5)

    // Summary
    doc.fontSize(11).font('Helvetica').fillColor('#334155').text(summary || '', { align: 'left', lineGap: 4 })
    doc.moveDown(1)

    // Matched Skills
    if (matchedSkills && matchedSkills.length > 0) {
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#94a3b8').text('MATCHED SKILLS FOR THIS ROLE', { characterSpacing: 1 })
      doc.moveDown(0.4)
      matchedSkills.forEach(skill => {
        doc.fontSize(11).font('Helvetica').fillColor('#15803d').text(`✓ ${skill}`, { lineGap: 3 })
      })
      doc.moveDown(1)
    }

    // All Skills
    if (skills && skills.length > 0) {
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#94a3b8').text('FULL SKILL SET', { characterSpacing: 1 })
      doc.moveDown(0.4)
      const skillLine = skills.filter(s => s.length > 0 && s.length < 40).join('  •  ')
      doc.fontSize(11).font('Helvetica').fillColor('#0f172a').text(skillLine, { lineGap: 4 })
      doc.moveDown(1)
    }

    // Footer
    doc.moveTo(50, doc.y).lineTo(560, doc.y).strokeColor('#e2e8f0').lineWidth(1).stroke()
    doc.moveDown(0.5)
    doc.fontSize(9).font('Helvetica').fillColor('#94a3b8').text('Generated by LiveProof — AI-powered resume matching', { align: 'center' })

    doc.end()

  } catch (err) {
    console.error('PDF Error:', err.message)
    res.status(500).json({ error: 'PDF generation failed' })
  }
})

module.exports = router
