const express = require('express')
const router = express.Router()
const puppeteer = require('puppeteer')

router.post('/generate', async (req, res) => {
  const { name, skills, matchedSkills, jobTitle, summary } = req.body

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', sans-serif; padding: 48px; color: #0f172a; }
        .header { border-bottom: 3px solid #0ea5e9; padding-bottom: 24px; margin-bottom: 32px; }
        .name { font-size: 36px; font-weight: 900; letter-spacing: -1px; }
        .title { font-size: 16px; color: #0ea5e9; font-weight: 600; margin-top: 4px; }
        .summary { font-size: 14px; color: #475569; margin-top: 12px; line-height: 1.6; }
        .section { margin-bottom: 28px; }
        .section-title { font-size: 11px; font-weight: 700; letter-spacing: 0.15em; text-transform: uppercase; color: #94a3b8; margin-bottom: 12px; }
        .skills-grid { display: flex; flex-wrap: wrap; gap: 8px; }
        .skill { background: #f0f9ff; color: #0369a1; font-size: 13px; font-weight: 600; padding: 6px 14px; border-radius: 20px; border: 1px solid #bae6fd; }
        .skill.matched { background: #f0fdf4; color: #15803d; border-color: #bbf7d0; }
        .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
        .generated { color: #0ea5e9; font-weight: 700; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="name">${name || 'LiveProof Candidate'}</div>
        <div class="title">${jobTitle || 'Full Stack Developer'}</div>
        <div class="summary">${summary || 'Experienced developer with strong full-stack skills.'}</div>
      </div>

      <div class="section">
        <div class="section-title">Matched Skills for this Role</div>
        <div class="skills-grid">
          ${(matchedSkills || []).map(s => `<span class="skill matched">✓ ${s}</span>`).join('')}
        </div>
      </div>

      <div class="section">
        <div class="section-title">Full Tech Stack</div>
        <div class="skills-grid">
          ${(skills || []).map(s => `<span class="skill">${s}</span>`).join('')}
        </div>
      </div>

      <div class="footer">
        Generated by <span class="generated">LiveProof</span> — AI-powered resume matching
      </div>
    </body>
    </html>
  `

  try {
    const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox'] })
    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: 'networkidle0' })
    const pdf = await page.pdf({ format: 'A4', printBackground: true })
    await browser.close()

    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', 'attachment; filename=liveproof-resume.pdf')
    res.send(pdf)
  } catch (err) {
    console.error('PDF Error:', err.message)
    res.status(500).json({ error: 'PDF generation failed' })
  }
})

module.exports = router